name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - feature/* 
  pull_request:
    branches: 
      - feature/*

permissions:
  contents: read
  packages: write

env:
  DOTNET_VERSION: "8.x"
  SOLUTION_FILE: "Pocs.Aspire.sln"
  REGISTRY: "ghcr.io"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
           token: ${{ github.token }}

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
         
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_FILE }} --configuration Release --no-restore --no-build

      - name : Publish
        run: dotnet publish ${{ env.SOLUTION_FILE }}  --configuration Release --no-restore --no-build

      - name: Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build docker image
        run: |
          docker build \
            --file src/Pocs.Aspire.ApiService/Dockerfile \
            --tag ${{ env.REGISTRY}}/${{ github.repository }}:latest \
            .

      - name: Publish docker image
        run: docker push ${{ env.REGISTRY}}/${{ github.repository }}:latest
